name: terraform-lint

on: [push, pull_request]

jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@main
    - name: Install ansible dependencies
      run: ansible-galaxy collection install community.general &&  ansible-galaxy collection install kubernetes.core
    - name: Lint Terraform
      uses: actionshub/terraform-lint@main
